apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autodeploydemoapp.webapi.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {
      "WebApi": {
        "Setting1": "{{ .Values.appsettings.setting1 }}",
        "Setting2": "{{ .Values.appsettings.setting2 }}"
      }
    }