apiVersion: v2
name: autodeploydemoapp
description: Umbrella chart for AutoDeployDemoApp including Web API and CronJob
type: application
version: 3.0.5
dependencies:
  - name: autodeploydemoapp-webapi
    version: 0.1.6
    repository: file://charts/autodeploydemoapp-webapi-chart
  - name: autodeploydemoapp-cronjob
    version: 0.2.2
    repository: file://charts/autodeploydemoapp-cronjob-chart
