apiVersion: v2
name: autodeploydemoapp
description: Umbrella chart for AutoDeployDemoApp including Web API and CronJob
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: autodeploydemoapp.webapi
    version: 0.0.1
    repository: file://../autodeploydemoapp-webapi-chart
  - name: autodeploydemoapp.cronjob
    version: 0.0.1
    repository: file://../autodeploydemoapp-cronjob-chart