ingress:
  enabled: true
  host: autodeploydemoapp.local
  port: 80

certificates:
  enabled: true
  installClusterIssuer: false
  issuerName: "selfsigned-issuer"  # use "letsencrypt-prod" in production
  commonName: autodeploydemoapp.local
  email: pascal@icatt.nl

service:
  type: LoadBalancer

appsettings:
  webapi:
    Setting1: "Value1"
    Setting2: "Value2"
  cronjob:
    schedule: "0 0 * * *"
    SettingA: "A"

config:
  globalSetting: "shared-value"

secrets:
  apiKey: "shared-api-key"

autodeploydemoapp-webapi:
  image:
    repository: "ghcr.io/pascalicatt/autodeploydemoapp.webapi"
    tag: "0.0.1-546f239"
    pullPolicy: IfNotPresent