apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autodeploydemoapp.cronjob.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {
      "cronJobMessage": "{{ .Values.appsettings.cronJobMessage }}"
    }