apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "autodeploydemoapp.cronjob.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: autodeploydemoapp-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
          restartPolicy: OnFailure