{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "autodeploydemoapp.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.certificates.issuerName }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.certificates.commonName }}
      secretName: {{ include "autodeploydemoapp.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "autodeploydemoapp.fullname" . }}-webapi-svc
                port:
                  number: {{ .Values.ingress.port }}
{{- end }}
