name: Main Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  version-check:
    uses: ./.github/workflows/version-check.yml
    with:
      chart_path: "charts/autodeploydemoapp-umbrella-chart/Chart.yaml"

  # Use the boolean output from the reusable workflow
  follow_up:
    runs-on: ubuntu-latest
    needs: version-check
    if: needs.version-check.outputs.version_updated == 'true'
    steps:
      - run: echo "Version was updated! Proceeding..."
