name: Reusable Version Check

on:
  workflow_call:
    inputs:
      chart_path:
        description: "Path to the Chart.yaml file"
        required: true
        type: string

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      version_updated: ${{ steps.set_output.outputs.version_updated }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
      - run: git fetch origin main
      - id: check
        run: |
          CHART="${{ inputs.chart_path }}"
          CUR_VER=$(yq eval '.version' $CHART)
          MAIN_VER=$(git show origin/main:$CHART | yq eval '.version' -)
          echo "Current: $CUR_VER, Main: $MAIN_VER"
      - id: set_output
        run: |
          echo "version_updated=[ "$CUR_VER" != "$MAIN_VER" ] >> $GITHUB_OUTPUT
          echo "version=$CUR_VER >> $GITHUB_OUTPU
